### ISSUE TITLE
Can't see any messages if the last message was more than 6 hours ago

### ISSUE THREAD

**Issue by asssaf** [asssaf/urbit-mobile-talk#3]
This can be fixed by using the "fetch last x messages" feature

- https://github.com/Fang-/arvo/commit/95e35ce2c9075ec3c1a7438835dc84a9eec22d0d
- https://github.com/urbit/arvo/issues/643
- https://github.com/urbit/arvo/pull/658

**Comment by Fang-** [comment]
The feature's been merged, and will be pushed out sometime today if everything proceeds without surprises. (:
